### ISSUE TITLE
Decrease button not updating it's style when clicked

### ISSUE THREAD

**Issue by iainheng** [WrathChaos/react-native-counter-input#8]
As title said, the decrease button not changing it appearance when clicked. 

Here is a gif demonstrate the issue. 

![decrease_button_problem](https://user-images.githubusercontent.com/3263759/235697929-754e9fcd-6f18-4f2b-8a4f-d07348aa2ee9.gif)

**Comment by kuraydev** [comment]
Hello @iainheng 
Thank you for reporting the issue. 

Edit: 

You're totally right. This feature is broken. I will fix it asap!

**Comment by kuraydev** [comment]
Hey again @iainheng 

I fixed the bug, can you please try it with the `2.0.1` version?


Thank you again for reporting the issue :)

**Comment by iainheng** [comment]
@WrathChaos Thanks for the fix 👍 

But I am getting this error now 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/3263759/235873763-bd4824fc-6446-4322-87d5-5becf103241c.png">

Did you forgot to include the local-assets in the build?

**Comment by kuraydev** [comment]
Hey @iainheng 

Today is a busy day, totally forgot that :) 

Thank you and I released the 2.0.2 and tested it. It should have been fixed. Can you please try again?

**Comment by iainheng** [comment]
No problem @WrathChaos. Totally understand that 🤣

I can confirm issue is fixed in 2.0.2. Thanks a lot for the quick fix. 👍
